services:
  web:
    build: .
    container_name: php-webserver
    ports:
      - "80:80"
    volumes:
      - ./:/app
    depends_on:
      - db
    networks:
      - webKasir

  db:
    image: postgres
    container_name: postgres
    environment:
      POSTGRES_PASSWORD: eka12345
      POSTGRES_USER: postgres
      POSTGRES_DB: webKasir
    volumes:
      - postgresql-data:/var/lib/postgresql/data
    networks:
      - webKasir
    ports:
      - "5432:5432"

networks:
  webKasir:
    driver: bridge

volumes:
  postgresql-data:
